### ISSUE TITLE
Randomized Reward Option

### ISSUE THREAD

**Issue by JoshGibson2005** [HalfloveJAR/DailyRewards2-Docs#2]
Hiya! Hope your day is going well!

I'm having issues with the plugin regarding setting it up, each time I edit it then look to reload the plugin it deletes all the stuff I've editted and added and replaces it with the default template, is this supposed too happen? Thank you so much!

**Comment by HalfloveJAR** [comment]
Hey Josh! I recommend restarting your server after making changes to the configuration file. This is because the menu is built and stored when the server first starts (to save resources), so the reload command won't affect the menu.

If you still have issues, do you mind sending me your config.yml and your console log so I can see if there is any errors?

Thanks!

**Comment by JoshGibson2005** [comment]
Thank you so much! I also have another question how would i make it so on lets say day six one of the rewards is a randomised spawner? I'm pretty clueless at this stuff so please forgive me

**Comment by HalfloveJAR** [comment]
Oh actually, you can only set up random rewards that with a third party plugin (like [CustomCommands](https://www.spigotmc.org/resources/customcommands-new-1-20-support.14363/) for example), and then add your custom command as a reward on the Daily Rewards configuration. That being said, the random reward feature is a really good idea and I will look into adding that functionality into the plugin as soon as I can. Thank you for the suggestion!

**Comment by JoshGibson2005** [comment]
No Problem, Thank you so much have a great day!

**Comment by HalfloveJAR** [comment]
Quick heads up, I got a random feature working during my dev time today -- I will make sure to include it in my next version release as soon as it is ready! 🙏

**Comment by HalfloveJAR** [comment]
This has been implemented in the latest update (2.0.2), you can see example usage here: https://github.com/HalfloveJAR/DailyRewards2-Docs/wiki/Creating-Custom-Days-(Reward-Groups)#making-a-reward-group-random

Thanks!
