### ISSUE TITLE
We should be able to edit the plugin gui

### ISSUE THREAD

**Issue by frknmrl** [HalfloveJAR/DailyRewards2-Docs#3]
My server version is 1.20.4,

We can't even edit the message content in the plugin's Gui, it would be nice if this could be fixed.

**Comment by frknmrl** [comment]
Also I can't add new rewards, after refreshing the plugin everything goes back to default settings.

**Comment by HalfloveJAR** [comment]
> Also I can't add new rewards, after refreshing the plugin everything goes back to default settings.

I couldn't replicate this issue, I believe you are making a mistake with the yml format. Put your config in something [like this](https://onlineyamltools.com/validate-yaml) to make sure you aren't messing up the formatting. If you are still having the issue please open a separate bug report with screenshots or a video of the issue happening so I can try to replicate it.

> My server version is 1.20.4,
> 
> We can't even edit the message content in the plugin's Gui, it would be nice if this could be fixed.

Fixing this in the newest version.

**Comment by HalfloveJAR** [comment]
> Also I can't add new rewards, after refreshing the plugin everything goes back to default settings.

Fixed in update 2.0.3, thanks for the report: https://www.spigotmc.org/resources/daily-rewards-2.115112/update?update=542767
