### ISSUE TITLE
Allow changing of timing format

### ISSUE THREAD

**Issue by rudde0** [HalfloveJAR/DailyRewards2-Docs#4]
**Is your feature request related to a problem? Please describe.**
Could you add timing formats into messages.yml?

I want to change text of "Hours" and "Minutes".

**Describe the solution/feature you'd like**
Add yaml keys such as `locale.hour:`, `locale.hours:`, `locale.minute:`, `locale.minutes:`.

**Comment by HalfloveJAR** [comment]
Added in version 2.0.5 released [here](https://www.spigotmc.org/resources/daily-rewards-2.115112/update?update=552971). Thanks for the suggestion.
